### ISSUE TITLE
後ろの画面と一緒に動かなくなった

### ISSUE THREAD

**Issue by shiratsumu** [shiratsumu/seirei.github.io#1]
@K-REBO[a](file:///C:/Users/saka/Documents/shiratsumu/web/index.html)

**Comment by K-REBO** [comment]
fixedは完全にpxとか%で固定なので動かんと思う
うごかしたくないんなら

1. 親要素に合わせてマージンで調整
``` HTML
#main {
  margin-left: 30px;
}
```

2. 親要素に合わせてうごく絶対位置
``` HTML 
#main {
  position:absolute;
  left:14%;
}
```

とかにするとか

**Comment by shiratsumu** [comment]
できた、サンキュな
margin_rightは動かんけど、leftは動く、わけわかめ

**Comment by shiratsumu** [comment]
だから左から調節頑張った

**Comment by K-REBO** [comment]
closeしとき
